# Generated by Django 2.0.1 on 2018-01-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0002_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='appartment',
            new_name='apartment',
        ),
    ]
