# Generated by Django 2.0.1 on 2018-01-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0003_auto_20180110_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='Athens', max_length=100),
            preserve_default=False,
        ),
    ]
