# Generated by Django 2.0.1 on 2018-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0004_apartment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
