# Generated by Django 2.0.1 on 2018-02-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0005_auto_20180201_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default='No descriptin provided by the owner', max_length=500),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
