# Generated by Django 2.0.1 on 2018-02-05 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0006_auto_20180204_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='pub_year',
        ),
        migrations.AddField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 5, 1, 4, 39, 453909, tzinfo=utc), verbose_name='date published'),
        ),
    ]
