# Generated by Django 2.0.1 on 2018-02-06 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0007_auto_20180205_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='photos',
            field=models.CharField(default='not_provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
