# Generated by Django 2.0.1 on 2018-02-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0008_auto_20180206_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photos',
            field=models.ImageField(default='static/assets/img/property_3.jpg', upload_to='static/assets/img/'),
        ),
    ]
