# Generated by Django 2.0.1 on 2018-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0009_auto_20180209_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photos',
            field=models.ImageField(default='', upload_to='static/assets/img/'),
        ),
    ]
