# Generated by Django 2.0.1 on 2018-02-10 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0011_remove_apartment_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='photos',
            field=models.CharField(default='do', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=datetime.date(2018, 2, 10), verbose_name='date published'),
        ),
    ]
