# Generated by Django 2.0.1 on 2018-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0012_auto_20180210_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photos',
            field=models.BinaryField(),
        ),
    ]
