# Generated by Django 2.0.1 on 2018-02-11 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yourhome', '0017_auto_20180211_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIfLogged', models.BooleanField(default='False')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=datetime.date(2018, 2, 11), verbose_name='date published'),
        ),
    ]
