# Generated by Django 2.0.1 on 2018-02-12 02:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yourhome', '0019_remove_checkuser_checkiflogged'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=datetime.date(2018, 2, 12), verbose_name='date published'),
        ),
    ]
