# Generated by Django 2.0.1 on 2018-02-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0022_auto_20180212_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
