# Generated by Django 2.0.1 on 2018-02-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0023_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='user',
        ),
    ]
