# Generated by Django 2.0.1 on 2018-02-13 01:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yourhome', '0024_remove_apartment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
                ('comment', models.TextField(default='No Comment provided by the visitor', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='apartments',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='pub_date',
            field=models.DateField(default=datetime.date(2018, 2, 13), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourhome.Apartment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
