# Generated by Django 2.0.1 on 2018-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0026_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
